spring:
  config:
    import:
      - classpath:/yml/application-local.yml
      - classpath:/yml/application-dev.yml
      - classpath:/yml/oauth2-local.yml
      - classpath:/yml/oauth2-dev.yml
  profiles:
    active: local

server:
  tomcat:
    keep-alive-timeout: 65000ms
