spring:
  config:
    import:
      - classpath:/yml/application-secret.yml
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dev-db.url}
    username: ${dev-db.username}
    password: ${dev-db.password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email-auth.username}
    password: ${email-auth.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 50000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  data:
    redis:
      host: ${dev-redis.host}
      port: ${dev-redis.port}
      password: ${dev-redis.password}

  elasticsearch:
    rest:
      uris: ${elasticsearch.rest.uris}
      username: ${elasticsearch.rest.username}
      password: ${elasticsearch.rest.password}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope: ${google.scope}
            redirect-uri: ${google.redirect-uri.dev}
            authorization-grant-type: authorization_code

          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            scope: ${kakao.scope}
            redirect-uri: ${kakao.redirect-uri.dev}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            provider: kakao

          naver:
            client-id: ${naver.client-id}
            client-secret: ${naver.client-secret}
            scope: ${naver.scope}
            redirect-uri: ${naver.redirect-uri.dev}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            provider: naver

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  swagger-ui:
    path: ${dev.swagger.path}

secret:
  key:
    access: ${jwt.secret.key.access}
    refresh: ${jwt.secret.key.refresh}

cloud:
  aws:
    region:
      static: ${aws.region.static}
    credentials:
      accessKey: ${aws.credentials.accessKey}
      secretKey: ${aws.credentials.secretKey}
    s3:
      bucket: ${aws.s3.bucket}